# Global setting
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'system-monitor'

# Rule setting
rule_files:
  - /etc/prometheus/alert_rules.yaml

# Alert setting
alerting:
  alertmanagers:
    - static_configs:
      - targets: ['alert-manager:9093']

# Target setting
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
        labels:
          instance: 'node'
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
        labels:
          group: 'cadvisor'

